version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/javascript-node:16-bullseye
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    links:
      - opensearch
    environment:
      ELASTIC_HOST: 'opensearch'

  opensearch:
    container_name: opensearch
    # restart: always
    image: opensearchproject/opensearch:1.3.20
    environment:
      discovery.type: 'single-node'
      ES_JAVA_OPTS: '-Xms1g -Xmx1g'
      plugins.security.disabled: 'true'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../../data:/usr/share/opensearch/data:cached
    #   - "../../opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
    #   - "./certs:/usr/share/opensearch/config/certificates:ro"
    ports:
      - 9200:9200
      - 9300:9300
