name: Update Data for SA

on:
  schedule:
    - cron: '48 01 21,28 2,5,8,11 *'
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-update.yml
    secrets:
      TF_VAR_ELASTIC_HOST: ${{ secrets.TF_VAR_ELASTIC_HOST }}
      TF_VAR_ELASTIC_PASSWORD: ${{ secrets.TF_VAR_ELASTIC_PASSWORD }}
      TF_VAR_ELASTIC_USERNAME: ${{ secrets.TF_VAR_ELASTIC_USERNAME }}
    with:
      state: SA
